FROM python:3.8-slim

WORKDIR /code
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0

COPY short_requirements.txt short_requirements.txt
RUN pip install -r short_requirements.txt
EXPOSE 5000
COPY . .
CMD ["flask", "run"]

## To build: call this from root project folder.
# docker build -t kerasapi:latest -f ./docker/DockerFile .

## To run the container using gpus and host ip.
# docker run --network=host --gpus all kerasapi

## Expose GPUs for use:
# Include the --gpus flag when you start a container
# to access GPU resources. Specify how many GPUs to use.
# For example:
# docker run -it --rm --gpus all ubuntu nvidia-smi

# https://docs.nvidia.com/deeplearning/frameworks/user-guide/index.html
# https://docs.docker.com/config/containers/resource_constraints/
