FROM python:3.8-slim

WORKDIR /code
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
# RUN apk add --no-cache gcc musl-dev linux-headers

COPY short_requirements.txt short_requirements.txt
RUN pip install -r short_requirements.txt
EXPOSE 5000
COPY . .
CMD ["flask", "run"]

# docker build -t benno4president/kerasapi:lastest -f ./docker/DockerFile .